// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;

namespace Application {
	public class BehindDetection : MonoBehaviour {
		int cars = 0;
		public BehindDetection () {
		}

		void OnTriggerEnter (Collider collider) {
			Debug.Log ("Collision " + collider.name);
			if (collider.name.Contains("Car")) {
				cars++;
				Debug.Log(cars + " cars");
			}
		}

		void OnTriggerExit() {
			if (collider.name.Contains("Car")) {
				cars--;
				Debug.Log(cars + " cars");
			}		
		}
	}
}

