// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;
namespace AssemblyCSharp {
	public class BikeChainSound : MonoBehaviour {

		CharacterController controller;
		public BikeChainSound () {
		}

		void Start() {
			controller = (CharacterController) gameObject.GetComponent<CharacterController>();
		}

		void Update() {
			gameObject.audio.volume = Remap(controller.velocity.magnitude, 0, 3, 0, .15f);
		}

		float Remap (float value, float low1, float high1, float low2, float high2) {
			return low2 + (value - low1) * (high2 - low2) / (high1 - low1);
		}
	}
}

