// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;

namespace Application {
	public class CarMoveTest : MonoBehaviour {

		public bool MoveXNotZ;
		public float StartPosition;
		public float EndPosition;
		public float Speed;

		public CarMoveTest () {
		}
		
		void Update() {
			Vector3 currentPosition = gameObject.transform.position;
			if (MoveXNotZ) {
				currentPosition.x = currentPosition.x + Speed;
				if (Speed > 0) {
					if (currentPosition.x > EndPosition) {
						currentPosition.x = StartPosition;
					}
				} else {
					if (currentPosition.x < EndPosition) {
						currentPosition.x = StartPosition;
					}
				}
			} else {
				currentPosition.z = currentPosition.z + Speed;
				if (Speed > 0) {
					if (currentPosition.z > EndPosition) {
						currentPosition.z = StartPosition;
					}
				} else {
					if (currentPosition.z < EndPosition) {
						currentPosition.z = StartPosition;
					}
				}
			}
			gameObject.transform.position = currentPosition;
		}
	}
}


